import type { Metadata } from "next";
import "../globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import Header from "@/components/header";
import { Poppins } from "next/font/google";
import { SanityLive } from "@/sanity/lib/live";
import Footer from "@/components/footer";

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["400", "600", "700"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
        {/* Apply the font to the body using className */}
        <body className={poppins.className}>
          <main>
            <Header />
            {children}
          </main>

          <SanityLive />
          <Footer />
        </body>
      </html>
    </ClerkProvider>
  );
}
